### ISSUE TITLE
[WARN]  runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by golf04** [nim4/DBShield#3]
Hi nim4,

I found this issue on DBShield when my website query database on port 5000 that DBShield listening.
Do you know how to fix it or i configured something wrong ?

# go run main.go
2016/12/29 09:45:41 [INFO]  Config file: /etc/dbshield.yml
2016/12/29 09:45:41 [INFO]  Listening: 0.0.0.0:5000
2016/12/29 09:45:41 [INFO]  Backend: mysql (127.0.0.1:3306)
2016/12/29 09:45:41 [INFO]  Protect: false
2016/12/29 09:45:41 [INFO]  Web interface on https://XXX.XXX.XXX.XXX:8070/
2016/12/29 09:46:14 [WARN]  runtime error: slice bounds out of range
2016/12/29 09:52:07 [WARN]  runtime error: slice bounds out of range
2016/12/29 09:52:11 [WARN]  runtime error: slice bounds out of range
2016/12/29 09:52:13 [WARN]  runtime error: slice bounds out of range

# /etc/dbshield.yml

```
##############################
### General               ###
#############################

# Operating mode
# possible values:
#       learning - add queries to training set (default)
#       protect - take action against abnormal queries
mode: learning

# DBMS type(default: mysql)
dbms: mysql

# IP address to listen on(default: 0.0.0.0)
listenIP: 0.0.0.0

# Port number to listen on (0 means dbms default port ex. 3306 for mysql)
listenPort: 5000

# IP address of the server
targetIP: 127.0.0.1

# Port number of the dbms (0 means dbms default port ex. 3306 for mysql)
targetPort: 3306

# TLS
tlsPrivateKey:  cert/server-key.pem
tlsCertificate: cert/server-cert.pem

# Directory to save internal database(default: in model directory under OS's temp directory)
dbDir: "/tmp/model/"

# Databasse synchronisation interval, 0 will force sync after each commit.
# Valid units are "ns", "us" (or "µs"), "ms", "s", "m" and "h". (default: 5s)
SyncInterval: 5s

#############################
### HTTP Service          ###
#############################
# Run http interface(default: yes)
http: yes

# Serve https (default: yes)
httpSSL: yes

# IP address to listen on(default: 127.0.0.1)
#httpIP: 127.0.0.1
httpIP: XXX.XXX.XXX.XXX

# Port number to listen on(default: 8070)
httpPort: 8070

# Password
httpPassword: admin01

#############################
### Protect               ###
#############################

# Action to take against abnormal requests
# possible values:
#       drop  - close the connection (default)
#       pass  - pass the query to server
action: drop

# Properties to check for abnormality
#
# possible values: (you can choose more than one - comma separated)
#       user     - username
#       source   - request sourece address
#
# Note: leave empty to avoid adiditional checks
additionalChecks:  user,source

#############################
### Logging               ###
#############################

# Log depth
#       1   warning
#       2   info
#       4   debug
# default: 3 (warning + info)
logLevel: 3

# Log path
# possible values:
#       /path/to/file
#       stdout
#       stderr (default)
logPath: stderr


```

**Comment by nim4** [comment]
Hi @golf04,

Thanks for taking the time to file an issue, Config file seems correct. to help tracing the problem can you change the logLevel to 7 and attach the output.

**Comment by golf04** [comment]
Thank for your reply nim4.
This is log config on /etc/dbshield.yml

```
#############################
### Logging               ###
#############################

# Log depth
#       1   warning
#       2   info
#       4   debug
# default: 3 (warning + info)
logLevel: 7
```

This is level7 log :

```
# go run main.go
2016/12/29 13:31:54 [INFO]  Config file: /etc/dbshield.yml
2016/12/29 13:31:54 [INFO]  Listening: 0.0.0.0:5000
2016/12/29 13:31:54 [INFO]  Backend: mysql (127.0.0.1:3306)
2016/12/29 13:31:54 [INFO]  Protect: false
2016/12/29 13:31:54 [INFO]  Web interface on https://XXX.XXX.XXX.XXX:8070/
2016/12/29 13:32:10 [DEBUG] Connected from: 127.0.0.1:47586
2016/12/29 13:32:10 [DEBUG] Connected to: 127.0.0.1:3306
2016/12/29 13:32:10 [DEBUG] Username: wordpress
2016/12/29 13:32:10 [WARN]  runtime error: slice bounds out of range
2016/12/29 13:32:11 [DEBUG] Connected from: 127.0.0.1:47594
2016/12/29 13:32:11 [DEBUG] Connected to: 127.0.0.1:3306
2016/12/29 13:32:11 [DEBUG] Username: wordpress
2016/12/29 13:32:11 [WARN]  runtime error: slice bounds out of range
2016/12/29 13:32:13 [DEBUG] Connected from: 127.0.0.1:47602
2016/12/29 13:32:13 [DEBUG] Connected to: 127.0.0.1:3306
2016/12/29 13:32:13 [DEBUG] Username: wordpress
2016/12/29 13:32:13 [WARN]  runtime error: slice bounds out of range
2016/12/29 13:32:13 [DEBUG] Connected from: 127.0.0.1:47610
2016/12/29 13:32:13 [DEBUG] Connected to: 127.0.0.1:3306
2016/12/29 13:32:13 [DEBUG] Username: wordpress
2016/12/29 13:32:13 [WARN]  runtime error: slice bounds out of range
2016/12/29 13:32:14 [DEBUG] Connected from: 127.0.0.1:47618
2016/12/29 13:32:14 [DEBUG] Connected to: 127.0.0.1:3306
2016/12/29 13:32:14 [DEBUG] Username: wordpress
2016/12/29 13:32:14 [WARN]  runtime error: slice bounds out of range
2016/12/29 13:33:10 [DEBUG] Connected from: 127.0.0.1:47626
2016/12/29 13:33:10 [DEBUG] Connected to: 127.0.0.1:3306
2016/12/29 13:33:10 [DEBUG] Username: wordpress
2016/12/29 13:33:10 [WARN]  runtime error: slice bounds out of range
```

**Comment by nim4** [comment]
I can't reproduce the problem on Wordpress on my localhost. It seems like a problem in query parsing phase, maybe we fail to handle backward compatibility. What is your MySQL version?(select @@version;)

**Comment by golf04** [comment]
Hi sorry for late reply,

My testing environment is
- MySQL 5.1.73
- Wordpress 3.9.14

**Comment by golf04** [comment]
Hi @nim4 any update ?

**Comment by nim4** [comment]
Hey @golf04, sorry for late reply, I was busy. 

 Can you comment out "defer handlePanic()" in dbshield/dbms/mysql.go and reproduce the bug so we see the trace of the problem.

**Comment by golf04** [comment]
Hi @nim4 ,

I've comment out as your suggested as you can see below 

```
#nano /github.com/nim4/DBShield/dbshield/dbms/mysql.go

//Close sockets
func (m *MySQL) Close() {
//       defer handlePanic()
        m.client.Close()
        m.server.Close()
}

//DefaultPort of the DBMS
func (m *MySQL) DefaultPort() uint {
        return 3306
}

//Handler gets incoming requests
func (m *MySQL) Handler() error {
//       defer handlePanic()
        defer m.Close()
```

After i run go run main.go and these error shown up 
```
[root@s1 DBShield]# go run main.go
2017/01/10 13:19:17 [INFO]  Config file: /etc/dbshield.yml
2017/01/10 13:19:17 [INFO]  Listening: 0.0.0.0:5000
2017/01/10 13:19:17 [INFO]  Backend: mysql (127.0.0.1:3306)
2017/01/10 13:19:17 [INFO]  Protect: false
2017/01/10 13:19:17 [INFO]  Web interface on https://XXX.XXX.XXX.XXX:8070/
2017/01/10 13:19:46 [DEBUG] Connected from: 127.0.0.1:33296
2017/01/10 13:19:46 [DEBUG] Connected to: 127.0.0.1:3306
2017/01/10 13:19:46 [DEBUG] Connected from: 127.0.0.1:33300
2017/01/10 13:19:46 [DEBUG] Connected to: 127.0.0.1:3306
2017/01/10 13:19:47 [DEBUG] Username: wordpress
panic: runtime error: slice bounds out of range

goroutine 22 [running]:
panic(0x853b60, 0xc42000c130)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/nim4/DBShield/dbshield/dbms.getUsernameDB(0xc4202865f4, 0x3f, 0x3f, 0x43, 0x43, 0x0, 0x0, 0x0, 0xc420036c90)
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/dbms/mysql.go:199 +0x330
github.com/nim4/DBShield/dbshield/dbms.(*MySQL).handleLogin(0xc42020f980, 0x90bb90, 0xc42020f980, 0xc420266600)
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/dbms/mysql.go:123 +0x15c
github.com/nim4/DBShield/dbshield/dbms.(*MySQL).Handler(0xc42020f980, 0x0, 0x0)
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/dbms/mysql.go:58 +0x93
github.com/nim4/DBShield/dbshield.handleClient(0xad54a0, 0xc4200242f0, 0xc420130b10, 0xc4200242b8, 0x0)
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/utils.go:147 +0x2ad
created by github.com/nim4/DBShield/dbshield.mainListner
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/dbshield.go:143 +0x3c8
exit status 2

```

**Comment by nim4** [comment]
Thanks a lot, that's really useful. can you add "logger.Debug(data)" on line 192 so we see the function input.

**Comment by golf04** [comment]
I've add "logger.Debug(data)" on line 192 as you request.
```
func getUsernameDB(data []byte) (username, db []byte) {
        if len(data) < 33 {
                return
        }
        pos := 32
        logger.Debug(data)
        nullByteIndex := bytes.IndexByte(data[pos:], 0x00)
        username = data[pos : nullByteIndex+pos]
        logger.Debugf("Username: %s", username)
        pos += nullByteIndex + 22
        nullByteIndex = bytes.IndexByte(data[pos:], 0x00)
        if nullByteIndex != 0 {
                db = data[pos : nullByteIndex+pos]
                logger.Debugf("Database: %s", db)
        }
        return
}

```

This is the return result
```
[root@s1 DBShield]# go run main.go
2017/01/10 13:35:47 [INFO]  Config file: /etc/dbshield.yml
2017/01/10 13:35:47 [INFO]  Listening: 0.0.0.0:5000
2017/01/10 13:35:47 [INFO]  Backend: mysql (127.0.0.1:3306)
2017/01/10 13:35:47 [INFO]  Protect: false
2017/01/10 13:35:47 [INFO]  Web interface on https://XXX.XXX.XXX.XXX:8070/
2017/01/10 13:35:50 [DEBUG] Connected from: 127.0.0.1:33316
2017/01/10 13:35:50 [DEBUG] Connected to: 127.0.0.1:3306
2017/01/10 13:35:50 [DEBUG] [133 162 2 0 0 0 0 64 8 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 119 111 114 100 112 114 101 115 115 0 20 160 48 188 42 109 22 114 130 140 18 125 5 18 255 112 121 245 179 115 102]
2017/01/10 13:35:50 [DEBUG] Username: wordpress
panic: runtime error: slice bounds out of range

goroutine 12 [running]:
panic(0x853b60, 0xc42000c130)
        /usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/nim4/DBShield/dbshield/dbms.getUsernameDB(0xc4201647d4, 0x3f, 0x3f, 0x43, 0x43, 0x0, 0x0, 0x0, 0xc420036c90)
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/dbms/mysql.go:199 +0x3db
github.com/nim4/DBShield/dbshield/dbms.(*MySQL).handleLogin(0xc4200c4240, 0x90bbb0, 0xc4200c4240, 0xc420168220)
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/dbms/mysql.go:123 +0x15c
github.com/nim4/DBShield/dbshield/dbms.(*MySQL).Handler(0xc4200c4240, 0x0, 0x0)
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/dbms/mysql.go:58 +0x93
github.com/nim4/DBShield/dbshield.handleClient(0xad54a0, 0xc4200242d8, 0xc42012eb10, 0xc4200242b8, 0x0)
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/utils.go:147 +0x2ad
created by github.com/nim4/DBShield/dbshield.mainListner
        /home/dan/bin/src/github.com/nim4/DBShield/dbshield/dbshield.go:143 +0x3c8
exit status 2

```

**Comment by nim4** [comment]
Can  you please join the gitter chat at https://gitter.im/DBShield/Lobby ?

**Comment by golf04** [comment]
Hi @nim4,

Any update ?

**Comment by nim4** [comment]
It should work now after MySQL packet reading modification in [https://github.com/nim4/DBShield/commit/f4110b61418aa38d0a53538579fe03bd715d4542](this commit)
