### ISSUE TITLE
Drop action cause DBShield existing from command line

### ISSUE THREAD

**Issue by qiwihui** [nim4/DBShield#6]
When using `protect` mode from command line, DBShield existed with errors. I think it may need to drop the connection without make itself existed. 

DBShield version: commit b07fb6e658e12343d1efb9cd9760628b0e83d323
Go version: go version go1.9 darwin/amd64

```
> $GOPATH/bin/DBShield -c /etc/dbshield.yml

....

2017/09/21 18:52:14 [DEBUG] Query: select * from first where iii='中文'
2017/09/21 18:52:14 [WARN]  Invalid pattern
panic: Dropping connection

goroutine 10 [running]:
github.com/nim4/DBShield/dbshield/utils.ActionDrop(0xc42013802d, 0x26)
        /Users/qiwihui/Development/gopath/src/github.com/nim4/DBShield/dbshield/utils/action.go:5 +0x39
github.com/nim4/DBShield/dbshield/dbms.processContext(0xc42013802d, 0x26, 0x3b, 0xc420078324, 0x4, 0x39, 0xc42001438c, 0x10, 0x10, 0xc42007833e, ...)
        /Users/qiwihui/Development/gopath/src/github.com/nim4/DBShield/dbshield/dbms/utils.go:321 +0x18c
github.com/nim4/DBShield/dbshield/dbms.(*MySQL).Handler(0xc4200ba240, 0x0, 0x0)
        /Users/qiwihui/Development/gopath/src/github.com/nim4/DBShield/dbshield/dbms/mysql.go:91 +0x528
github.com/nim4/DBShield/dbshield.handleClient(0x1865d00, 0xc42000e568, 0xc420118090, 0xc420124008, 0x0)
        /Users/qiwihui/Development/gopath/src/github.com/nim4/DBShield/dbshield/utils.go:161 +0x350
created by github.com/nim4/DBShield/dbshield.mainListner
        /Users/qiwihui/Development/gopath/src/github.com/nim4/DBShield/dbshield/dbshield.go:162 +0x38a

```

sql statement: `select * from first where iii='中文';` where there is no `iii` in my `first` table

**Comment by nim4** [comment]
I commented out the `defer handlePanic()` while debugging  #5, uncommenting it should fix this
